services:
  db:
    image: postgres:15
    container_name: aprimorar_db
    environment:
      POSTGRES_DB: aprimorar
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  app:
#    build: .
#    container_name: spring_app
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: mypassword

volumes:
  db_data: